# EDA 

Initial setup
```{r}
library(dplyr)        # A package for data manipulation
library(sf)           # Simple feature for R
library(spdep)        # Functions and tests for evaluating spatial patterns 
library(tidyr)        # Tools to create tidy data
library(INLA)         # Integrated Nested Laplace Approximation package
library(ggplot2)      # A package for creating maps and graphs
library(viridis)      # A package providing color palettes 
library(patchwork)    # A package to compose plots
library(knitr)
library(kableExtra)
library(rstudioapi)
library(ggplot2)
library(scales)


rm(list=ls())
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
load("../CrimeUttarPradesh.RData")
```

```{r}
# Plot map of UP

carto_up <- st_as_sf(carto_up)

ggplot() + 
  geom_sf(data = carto_up, color = "blue", fill = "white") + 
  coord_sf() +    #axis limits and CRS
  theme_bw() +    # dark-on-light theme
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12))
```


### 1 - Summary statistics table

```{r}

# Calculate rates per 100,000 women
data$rape_rate_per100k <- data$rape / data$pop * 100000
data$dowry_rate_per100k <- data$dowry/ data$pop * 100000

# Summary table
year_agg <- data %>% group_by(year) %>% summarise(rape_obs = sum(rape),
                                                  rape_exp = sum(e_rape),
                                                  dowry_obs = sum(dowry),
                                                  dowry_exp = sum(e_dowry),
                                                  total_pop = sum(pop),
                                                  rape_crude_rate = rape_obs / total_pop * 100000,
                                                  dowry_crude_rate = dowry_obs / total_pop * 100000,
                                                  max_rape_region = dist[which.max(rape_rate_per100k)],
                                                  max_rape_rate = max(rape_rate_per100k),
                                                  min_rape_region = dist[which.min(rape_rate_per100k)],
                                                  min_rape_rate = min(rape_rate_per100k),
                                                  max_dowry_region = dist[which.max(dowry_rate_per100k)],
                                                  max_dowry_rate = max(dowry_rate_per100k),
                                                  min_dowry_region = dist[which.min(dowry_rate_per100k)],
                                                  min_dowry_rate = min(dowry_rate_per100k))

View(year_agg)
```

```{r, fig.width=10, fig.height=12}
# Visualise summary stats - crude rates

year_agg_vis <- year_agg %>% mutate(
  'Year' = year,
  'Rape' = round(rape_crude_rate, 1),
  'Dowry' = round(dowry_crude_rate, 1),
  'Higest Rape' = paste0(max_rape_region, " (", round(max_rape_rate, 1), ")"),
  'Lowest Rape' = paste0(min_rape_region, " (", round(min_rape_rate, 1), ")"),
  'Highest Dowry'= paste0(max_dowry_region, " (", round(max_dowry_rate, 1), ")"),
  'Lowest Dowry' = paste0(min_rape_region, " (", round(min_dowry_rate, 1), ")") ) %>% 
  select( 'Year', 'Rape', 'Dowry', 'Higest Rape', 'Lowest Rape', 'Highest Dowry', 'Lowest Dowry')

reg_table <- knitr::kable(year_agg_vis, caption = "Yearly summary of crude crime rates (per 100,000 women)") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "center")

save_kable(reg_table, file = "reg_table.png")

```

### 2 - Temporal evolution

```{r}

ggplot(year_agg_vis, aes(x = Year)) +
  geom_line(aes(y=Rape, color = "Rape")) + 
  geom_line(aes(y=Dowry, color = "Dowry")) + theme_minimal() +
  labs(title = "Temporal evolution of crude rates (per 100,000) of Rape and Dowry Crime", 
       x = "Year", y = "Crude Rate", color = "Crime Type")
```
#### 2b - Spaghetti plots
These could be useful to make a point that the rates are highly variable and therefore spatial smoothing is needed

```{r}

color_map <- c(
  "Dowry: State Average" = "#8E44AD",
  "Rape: State Average" = "#21918C",
  "Individual Districts" = "lightgray"
)
dummy_df <- data.frame(
  x = mean(range(data$year)), 
  y = mean(c(data$dowry_rate_per100k, year_agg$dowry_crude_rate), na.rm = TRUE)
)

p_dowry <- ggplot() + 
  geom_line(data=data, aes(x=year, y=dowry_rate_per100k, group=ID_area), color = "lightgray", alpha=0.7, show.legend = FALSE) +
  geom_line(data=year_agg, aes(x=year, y=dowry_crude_rate, color = "Dowry: State Average"), size = 1.5) + 
  
  # some dummy lines below for arrangment of legends
  geom_line(data = dummy_df, # dummy space for legend
            aes(x = x, y = y, color = "Individual Districts"), size = 1, alpha = 0.6, show.legend = TRUE) +
  geom_line(data = dummy_df, aes(x = x, y = y, color = "Rape: State Average"), size = 1, alpha = 0, show.legend = TRUE) +
  
  scale_color_manual(name = "Legend", values = color_map) +
  theme(legend.position = "right") +
  labs( y = "Crude Rate of Dowry Crime", x = "Year") + 
  theme_minimal()

p_rape <- ggplot() + 
  geom_line(data=data, aes(x=year, y=rape_rate_per100k, group=ID_area), color = "lightgray", alpha=0.7, show.legend = FALSE) +
  geom_line(data=year_agg, aes(x=year, y=rape_crude_rate, color = "Rape: State Average"), size = 1.5) + 
  
  # Dummy lines 
  geom_line(data = dummy_df, # dummy space for legend
            aes(x = x, y = y, color = "Individual Districts"), size = 1, alpha = 0.6, show.legend = TRUE) +
  geom_line(data = dummy_df, aes(x = x, y = y, color = "Dowry: State Average"), size = 1, alpha = 0, show.legend = TRUE) +
  
  scale_color_manual(name = "Legend", values = color_map) +
  theme(legend.position = "right") +
  labs(y = "Crude Rate of Rape", x = "Year") + 
  theme_minimal()

(p_dowry | p_rape) +
  plot_layout(guides = "collect") +
  plot_annotation(title = "Crude Rates of Rape and Dowry Crime in Uttar Pradesh (2001–2014)")

```


### 3 - Maps of crude rates

```{r}

# Summary stats
cuts = c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,8.5,9)

dist_rates <- data %>%
  group_by(ID_area) %>%
  summarise(
    total_rape = sum(rape),
    total_dowry = sum(dowry),
    total_pop = sum(pop),
    rape_rate = total_rape / total_pop * 100000,
    dowry_rate = total_dowry / total_pop * 100000
  ) %>% mutate(
    rape_rate_cut = cut(rape_rate, cuts),
    dowry_rate_cut = cut(dowry_rate, cuts)
  )

```

```{r}
# Plot of a single map
map_rates <- left_join(carto_up, dist_rates, by = c("ID_area" = "ID_area"))


ggplot() + geom_sf(data=map_rates, aes(fill=rape_rate), col=NA)  + 
  scale_fill_viridis_c(name = "Crude Rape Rate\n(per 100,000)", labels = label_comma(accuracy = 1)) +theme_bw()


```


```{r}
# Plot of multiple maps

map_rates_long <- map_rates %>% # Making long-format data
  select(ID_area, geometry, rape_rate, dowry_rate) %>%
  pivot_longer(cols = c(rape_rate, dowry_rate), names_to = "CrimeType", values_to = "Rate") %>%
  mutate(CrimeType = recode(CrimeType, rape_rate = "Rape",dowry_rate = "Dowry")
  )

ggplot(map_rates_long) +
  geom_sf(aes(fill = Rate), color = NA) +
  scale_fill_viridis_c(
    name = "Crude Rate\n(per 100,000)",
    labels = label_comma(accuracy = 1)
  ) +
  facet_wrap(~ CrimeType) + # set ncol=1 argument if want top and bottom
  labs(
    title = "Crude Rates by District (2001–2014)"
  ) +
  theme_bw()
```


